### ISSUE TITLE
Run sqliteboy on android

### ISSUE THREAD

**Issue by mvbasov** [nopri/sqliteboy#2]
Thank you for sqliteboy!

I wish provide you insruction how to run sqliteboy on Android using Termux:

---
- Install Termux from [Google Play Store](https://play.google.com/store/apps/details?id=com.termux) or from [F-Droid](https://f-droid.org/app/com.termux)
- Start Termux and run the following commands:
```
pkg install git python2
pip2 install web.py
git clone https://github.com/nopri/sqliteboy
python2 sqliteboy/sqliteboy.py example.sqlite
```
- Open http://localhost:11738/ link in your browser.
- To stop running sqliteboy server switch to Termux session an press `Ctrl-c` and then `Ctrl-d` to close Termux session.
---
If you wish you may put it to your documentation.
It created by me and checked on Android 6.0.1 and Android 9.0 systems.

**Comment by mvbasov** [comment]
![Screenshot_20191214-222140](https://user-images.githubusercontent.com/5613740/70853507-f5d22c00-1ebf-11ea-807a-67b5721bc055.png)
Unfortunately report lab is not availabel in this environment.

**Comment by nopri** [comment]
Hello,

Thank you very much for using SQLiteBoy and also for the additional documentation. 

Along with related pull requests by you (#3 and #4), may I suggest that you create a fork of SQLiteBoy and continue the development? 

This is because SQLiteBoy is now under maintenance for bug fix only and probably no new features will be added. 

Best regards,
Nop

**Comment by mvbasov** [comment]
Thank you for answer.

I understand you position. Close this issue and reject my pull requests. It need to set correct status for both projects.
I will rename my fork of your project (to SQLiteBoy3, may be) to indicate difference.

Thank you, again for SQLiteBoy!

**Comment by nopri** [comment]
Hello,

Thank you very much for your understanding. 

Wish you all the best for your SQLiteBoy fork. 

Best regards,
Nop
