### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mitya12342** [nopri/sqliteboy#5]
Hello! Am I doing something wrong? 
```
$ python sqliteboy.py data.sqlite 9999
  File "sqliteboy.py", line 1099
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by nopri** [comment]
Hello,

Thank you for using SQLiteBoy. 

Regarding the error message, are you using Python 3.x, by any chance? 

Please note that SQLiteBoy can only run on Python 2.x (tested on Python 2.7). 

Regards,
Nop
